### ISSUE TITLE
推广部 4.3 Q3 质疑

### ISSUE THREAD

**Issue by szxzip** [17999824wyj/NEUP-preTest#1]
第三题: “[HTML 标记语言](https://blog.csdn.net/pan_junbiao/article/details/98449634?ops_request_misc=%257B%2522request%255Fid%2522%253A%25227718C80B-BAEE-4DE3-9CC0-150205567D69%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=7718C80B-BAEE-4DE3-9CC0-150205567D69&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-2-98449634-null-null.142^v100^pc_search_result_base5&utm_term=%E6%A0%87%E8%AE%B0%E8%AF%AD%E8%A8%80&spm=1018.2226.3001.4187)，通过这个链接，学习 markdown 的语法。”

链接内容似乎是HTML的语法，并没有找到Markdown相关内容。
不知是编写者的疏漏，还是我理解有误。

此致

**Comment by 17999824wyj** [comment]
修改完毕，感谢你的细心！

这个 Issue 会在我的补丁部署完毕后关闭。
